local data = require("core.data")

local menu_script = "menu:/menu#script"
local game_script = "game:/game#script"

function on_message(self, message_id, message, sender)
	if message_id == hash("on_input") then
		if data.cur_scene == data.SCENE_GAME then
			msg.post(game_script, "on_input", message)
		elseif data.cur_scene == data.SCENE_MENU then
			msg.post(menu_script, "on_input", message)
		elseif data.cur_scene == data.SCENE_NONE then
			return
		end
	end
end
