local list_menu = require("menu.list_menu")

function init(self)
	msg.post(".", "acquire_input_focus")
end

local function process_input(self, action_id, action)
	if not action.pressed then return end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("on_input") then
		process_input(self, message.action_id, message.action)
	end
end

function on_input(self, action_id, action)
	msg.post("#", "on_input", { action_id = action_id, action = action })
end
